name: CI (main-ui)

on:
  push:
    branches: [ "main" ]
    paths:
      - "apps/main-ui/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "apps/main-ui/**"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

jobs:
  build:
    name: CI (main-ui)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: false

      - name: Configure git safe.directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE" || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # ¡Importante! Solo el lockfile real del workspace que se builda
          cache-dependency-path: apps/main-ui/package-lock.json

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Install deps (robusto)
        working-directory: apps/main-ui
        run: |
          npm ci || { rm -rf node_modules package-lock.json && npm install; }

      - name: Build with diagnostics (TS 5.4.5 + Vite)
        working-directory: apps/main-ui
        run: |
          set -Eeuo pipefail
          echo "::group::tsc (TS 5.4.5)"
          npx -y -p typescript@5.4.5 tsc -b 2>&1 | tee ci-tsc.log
          echo "::endgroup::"
          echo "::group::vite build"
          npx vite build 2>&1 | tee ci-vite.log
          echo "::endgroup::"

      - name: Upload CI debug logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug-logs
          path: |
            apps/main-ui/ci-*.log
          if-no-files-found: warn
          retention-days: 3
