name: ci

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      HUSKY: 0
      GIT_TRACE: 1
      GIT_TRACE_SETUP: 1
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure git for CI
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "/github/workspace"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure tags (some builds call `git describe`)
        run: |
          git fetch --tags --force || true
          git describe --always --dirty || echo "[diag] no tags available"

      - name: Wrap git to log every call
        run: |
          mkdir -p "$HOME/bin"
          cat > "$HOME/bin/git" <<'BASH'
          #!/usr/bin/env bash
          echo "[GIT WRAP] pwd=$(pwd) args=$*" >&2
          exec /usr/bin/git "$@"
          BASH
          chmod +x "$HOME/bin/git"
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Quick git sanity
        run: |
          set -x
          git rev-parse --is-inside-work-tree
          git rev-parse --abbrev-ref HEAD
          git rev-parse HEAD

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (root)
        run: npm ci || (rm -rf node_modules package-lock.json && npm install)

      - name: Build UI kit
        run: npm run -w packages/ui build

      - name: Build main-ui
        run: npm run -w apps/main-ui build
