name: CI (main-ui)

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'apps/main-ui/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'apps/main-ui/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false  # evita cualquier intento de procesar submodules (p.ej. Landpage)

      - name: Remove unused Landpage dir (if present)
        run: |
          if [ -d "Landpage" ]; then
            rm -rf Landpage
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (workspaces)
        run: npm ci --workspaces

      - name: Build main-ui (forces TS 5.4.5 via npm script)
        run: npm run -w apps/main-ui build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-ui-dist
          path: apps/main-ui/dist
          if-no-files-found: error
