name: CI (main-ui)

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'apps/main-ui/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'apps/main-ui/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Remove unused Landpage dir (if present)
        run: |
          if [ -d "Landpage" ]; then rm -rf Landpage; fi
          if [ -f ".gitmodules" ]; then rm -f .gitmodules; fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Instalación robusta SOLO en apps/main-ui
      - name: Install deps (apps/main-ui only, with fallback)
        working-directory: apps/main-ui
        run: |
          set -e
          echo ">>> npm ci (workspace)"
          if ! npm ci; then
            echo ">>> npm ci falló; limpiando y usando npm install"
            rm -rf node_modules package-lock.json
            npm install
          fi

      - name: Print versions (diagnóstico)
        run: |
          node -v
          npm -v
          npx -y -p typescript@5.4.5 tsc -v

      - name: Build main-ui (force TS 5.4.5)
        working-directory: apps/main-ui
        run: |
          npx -y -p typescript@5.4.5 tsc -b
          npx vite build

      - name: Show dist
        run: ls -la apps/main-ui/dist || true

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-ui-dist
          path: apps/main-ui/dist
          if-no-files-found: error
