name: CI (main-ui)

on:
  push:
    branches: [main]
    paths:
      - "apps/main-ui/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/main-ui/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ci-main-ui-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: CI (main-ui)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/main-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          # Importante: sin cache para no depender de package-lock
          check-latest: true

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Install (tolerante)
        run: |
          # Si existe lockfile usa ci, si no, instala normal
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Build (TypeScript 5.4.5 + Vite) con logs
        run: |
          set -euo pipefail
          echo ">>> TSC 5.4.5"
          npx -y -p typescript@5.4.5 tsc -b 2>&1 | tee ./ci-tsc.log
          echo ">>> Vite build (usando npx)"
          npx -y -p vite@5 vite build 2>&1 | tee ./ci-vite.log

      - name: Subir logs (siempre)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug-logs
          path: apps/main-ui/ci-*.log
          if-no-files-found: warn
