name: CI (main-ui)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-main-ui:
    name: CI (main-ui)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: false   # evitamos el submodule "Landpage"

      - name: Git safe.directory (evitar warnings)
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE" || true

      - name: Setup Node.js (sin cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Install deps (prefer ci si hay lock; si no, install)
        working-directory: apps/main-ui
        run: |
          set -euo pipefail
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (TypeScript 5.4.5 + Vite) con logs
        working-directory: apps/main-ui
        env:
          CI: "true"
        run: |
          set -euo pipefail
          npx -y -p typescript@5.4.5 tsc -b 2>&1 | tee ci-tsc.log
          vite build 2>&1 | tee -a ci-vite.log

      - name: Subir artefactos de diagnóstico
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug-logs
          path: |
            apps/main-ui/ci-tsc.log
            apps/main-ui/ci-vite.log
          if-no-files-found: ignore
